### ISSUE TITLE
土木工程下雨表示很赞

### ISSUE THREAD

**Issue by Hazard804** [BillYang2016/CQU-class2ics#2]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Hazard804** [comment]
![image](https://user-images.githubusercontent.com/82299110/133017477-6da77778-1efd-4a44-8a13-7247e0f4d5ab.png)
你好想请问一下出现这个报错是缺少什么库嘛

**Comment by BillYang2016** [comment]
这个问题可能是课程数据不全，你可以手动修复一下（

**Comment by BillYang2016** [comment]
如果课程安排时间未分配，则会如此报错
已经添加了错误提示，并提交至最新版本
